const checkAuth=()=>{
    try {
        
    } catch (error) {
        
    }
}